name: Get IP Address

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  get_ip_address:
    runs-on: ubuntu-latest
    steps:
      - name: Get public IP address
        id: get_ip
        run: echo "::set-output name=ip_address::$(curl -s https://api.ipify.org)"

      - name: Display IP address
        run: echo "The public IP address is ${{ steps.get_ip.outputs.ip_address }}"
