name: Get ISP Information

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  get_isp_info:
    runs-on: ubuntu-latest
    steps:
      - name: Get public IP address
        id: get_ip
        run: echo "::set-output name=ip_address::$(curl -s https://api.ipify.org)"

      - name: Retrieve ISP information
        id: get_isp
        run: |
          isp_info=$(curl -s "https://ipinfo.io/${{ steps.get_ip.outputs.ip_address }}/json")
          echo "::set-output name=isp::$(echo $isp_info | jq -r '.org')"

      - name: Display ISP information
        run: echo "The ISP is ${{ steps.get_isp.outputs.isp }}"
